version: "3"
services:
  mastersplay_app:
    build: .
    container_name: mastersplat_app
    restart: always
    user: "root"
    working_dir: /home/node/app/server
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
